package calc;


/**
* calc/CalculatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculator.idl
* Saturday, May 22, 2010 2:46:39 AM EEST
*/

public interface CalculatorOperations 
{
  long aduna (long a, long b);
  long scade (long a, long b);
  long inmulteste (long a, long b);
  long imparte (long a, long b);
  String baza2 (long n);
} // interface CalculatorOperations
