package calc;

/**
* calc/CalculatorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculator.idl
* Saturday, May 22, 2010 2:46:39 AM EEST
*/

public final class CalculatorHolder implements org.omg.CORBA.portable.Streamable
{
  public calc.Calculator value = null;

  public CalculatorHolder ()
  {
  }

  public CalculatorHolder (calc.Calculator initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = calc.CalculatorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    calc.CalculatorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return calc.CalculatorHelper.type ();
  }

}
