package calc;


/**
* calc/CalculatorPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculator.idl
* Saturday, May 22, 2010 2:46:39 AM EEST
*/

public abstract class CalculatorPOA extends org.omg.PortableServer.Servant
 implements calc.CalculatorOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("aduna", new java.lang.Integer (0));
    _methods.put ("scade", new java.lang.Integer (1));
    _methods.put ("inmulteste", new java.lang.Integer (2));
    _methods.put ("imparte", new java.lang.Integer (3));
    _methods.put ("baza2", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // calc/Calculator/aduna
       {
         long a = in.read_longlong ();
         long b = in.read_longlong ();
         long $result = (long)0;
         $result = this.aduna (a, b);
         out = $rh.createReply();
         out.write_longlong ($result);
         break;
       }

       case 1:  // calc/Calculator/scade
       {
         long a = in.read_longlong ();
         long b = in.read_longlong ();
         long $result = (long)0;
         $result = this.scade (a, b);
         out = $rh.createReply();
         out.write_longlong ($result);
         break;
       }

       case 2:  // calc/Calculator/inmulteste
       {
         long a = in.read_longlong ();
         long b = in.read_longlong ();
         long $result = (long)0;
         $result = this.inmulteste (a, b);
         out = $rh.createReply();
         out.write_longlong ($result);
         break;
       }

       case 3:  // calc/Calculator/imparte
       {
         long a = in.read_longlong ();
         long b = in.read_longlong ();
         long $result = (long)0;
         $result = this.imparte (a, b);
         out = $rh.createReply();
         out.write_longlong ($result);
         break;
       }

       case 4:  // calc/Calculator/baza2
       {
         long n = in.read_longlong ();
         String $result = null;
         $result = this.baza2 (n);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:calc/Calculator:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Calculator _this() 
  {
    return CalculatorHelper.narrow(
    super._this_object());
  }

  public Calculator _this(org.omg.CORBA.ORB orb) 
  {
    return CalculatorHelper.narrow(
    super._this_object(orb));
  }


} // class CalculatorPOA
