/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class app_Calculator */

#ifndef _Included_app_Calculator
#define _Included_app_Calculator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     app_Calculator
 * Method:    aduna
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_app_Calculator_aduna
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     app_Calculator
 * Method:    scade
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_app_Calculator_scade
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     app_Calculator
 * Method:    inmulteste
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_app_Calculator_inmulteste
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     app_Calculator
 * Method:    imparte
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_app_Calculator_imparte
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
