/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class app_NativePI */

#ifndef _Included_app_NativePI
#define _Included_app_NativePI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     app_NativePI
 * Method:    PI
 * Signature: (II)D
 */
JNIEXPORT jdouble JNICALL Java_app_NativePI_PI
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
