/*
 * This file was generated by orbit-idl-2 - DO NOT EDIT!
 */

#include <string.h>
#define ORBIT2_STUBS_API
#include "Calculator.h"

static ORBitSmallSkeleton get_skel_small_calc_Calculator(POA_calc_Calculator *servant,
const char *opname,gpointer *m_data, gpointer *impl)
{
switch(opname[0]) {
case 'a':
if(strcmp((opname + 1), "duna")) break;
*impl = (gpointer)servant->vepv->calc_Calculator_epv->aduna;
{ORBit_IInterface *volatile _t_=&calc_Calculator__iinterface;*m_data = (gpointer)&_t_->methods._buffer [0];}
return (ORBitSmallSkeleton)_ORBIT_skel_small_calc_Calculator_aduna;
break;
case 'b':
if(strcmp((opname + 1), "aza2")) break;
*impl = (gpointer)servant->vepv->calc_Calculator_epv->baza2;
{ORBit_IInterface *volatile _t_=&calc_Calculator__iinterface;*m_data = (gpointer)&_t_->methods._buffer [4];}
return (ORBitSmallSkeleton)_ORBIT_skel_small_calc_Calculator_baza2;
break;
case 'i':
switch(opname[1]) {
case 'm':
if(strcmp((opname + 2), "parte")) break;
*impl = (gpointer)servant->vepv->calc_Calculator_epv->imparte;
{ORBit_IInterface *volatile _t_=&calc_Calculator__iinterface;*m_data = (gpointer)&_t_->methods._buffer [3];}
return (ORBitSmallSkeleton)_ORBIT_skel_small_calc_Calculator_imparte;
break;
case 'n':
if(strcmp((opname + 2), "multeste")) break;
*impl = (gpointer)servant->vepv->calc_Calculator_epv->inmulteste;
{ORBit_IInterface *volatile _t_=&calc_Calculator__iinterface;*m_data = (gpointer)&_t_->methods._buffer [2];}
return (ORBitSmallSkeleton)_ORBIT_skel_small_calc_Calculator_inmulteste;
break;
default: break; 
}
break;
case 's':
if(strcmp((opname + 1), "cade")) break;
*impl = (gpointer)servant->vepv->calc_Calculator_epv->scade;
{ORBit_IInterface *volatile _t_=&calc_Calculator__iinterface;*m_data = (gpointer)&_t_->methods._buffer [1];}
return (ORBitSmallSkeleton)_ORBIT_skel_small_calc_Calculator_scade;
break;
default: break; 
}
return NULL;
}

void POA_calc_Calculator__init(PortableServer_Servant servant,
CORBA_Environment *env)
{
  static PortableServer_ClassInfo class_info = {NULL, (ORBit_small_impl_finder)&get_skel_small_calc_Calculator, "IDL:calc/Calculator:1.0", &calc_Calculator__classid, NULL, &calc_Calculator__iinterface};
  PortableServer_ServantBase__init (       ((PortableServer_ServantBase *)servant), env);
   ORBit_skel_class_register (&class_info,
   (PortableServer_ServantBase *)servant, POA_calc_Calculator__fini,
   ORBIT_VEPV_OFFSET (POA_calc_Calculator__vepv, calc_Calculator_epv),
   (CORBA_unsigned_long) 0);}

void POA_calc_Calculator__fini(PortableServer_Servant servant,
CORBA_Environment *env)
{
  PortableServer_ServantBase__fini(servant, env);
}

