/*
 * This file was generated by orbit-idl-2 - DO NOT EDIT!
 */

#include <string.h>
#define ORBIT2_STUBS_API
#include "Calculator.h"

CORBA_long_long calc_Calculator_aduna(calc_Calculator _obj, const CORBA_long_long a, const CORBA_long_long b, CORBA_Environment *ev){
CORBA_long_long _ORBIT_retval;
gpointer _args[2];
_args[0] = (gpointer)&a;
_args[1] = (gpointer)&b;
ORBit_c_stub_invoke (_obj, &calc_Calculator__iinterface.methods, 0, &_ORBIT_retval, _args, NULL, ev, calc_Calculator__classid, G_STRUCT_OFFSET (POA_calc_Calculator__epv, aduna),
(ORBitSmallSkeleton) _ORBIT_skel_small_calc_Calculator_aduna);

return _ORBIT_retval;
}
CORBA_long_long calc_Calculator_scade(calc_Calculator _obj, const CORBA_long_long a, const CORBA_long_long b, CORBA_Environment *ev){
CORBA_long_long _ORBIT_retval;
gpointer _args[2];
_args[0] = (gpointer)&a;
_args[1] = (gpointer)&b;
ORBit_c_stub_invoke (_obj, &calc_Calculator__iinterface.methods, 1, &_ORBIT_retval, _args, NULL, ev, calc_Calculator__classid, G_STRUCT_OFFSET (POA_calc_Calculator__epv, scade),
(ORBitSmallSkeleton) _ORBIT_skel_small_calc_Calculator_scade);

return _ORBIT_retval;
}
CORBA_long_long calc_Calculator_inmulteste(calc_Calculator _obj, const CORBA_long_long a, const CORBA_long_long b, CORBA_Environment *ev){
CORBA_long_long _ORBIT_retval;
gpointer _args[2];
_args[0] = (gpointer)&a;
_args[1] = (gpointer)&b;
ORBit_c_stub_invoke (_obj, &calc_Calculator__iinterface.methods, 2, &_ORBIT_retval, _args, NULL, ev, calc_Calculator__classid, G_STRUCT_OFFSET (POA_calc_Calculator__epv, inmulteste),
(ORBitSmallSkeleton) _ORBIT_skel_small_calc_Calculator_inmulteste);

return _ORBIT_retval;
}
CORBA_long_long calc_Calculator_imparte(calc_Calculator _obj, const CORBA_long_long a, const CORBA_long_long b, CORBA_Environment *ev){
CORBA_long_long _ORBIT_retval;
gpointer _args[2];
_args[0] = (gpointer)&a;
_args[1] = (gpointer)&b;
ORBit_c_stub_invoke (_obj, &calc_Calculator__iinterface.methods, 3, &_ORBIT_retval, _args, NULL, ev, calc_Calculator__classid, G_STRUCT_OFFSET (POA_calc_Calculator__epv, imparte),
(ORBitSmallSkeleton) _ORBIT_skel_small_calc_Calculator_imparte);

return _ORBIT_retval;
}
CORBA_string calc_Calculator_baza2(calc_Calculator _obj, const CORBA_long_long n, CORBA_Environment *ev){
CORBA_string _ORBIT_retval;
gpointer _args[1];
_args[0] = (gpointer)&n;
ORBit_c_stub_invoke (_obj, &calc_Calculator__iinterface.methods, 4, &_ORBIT_retval, _args, NULL, ev, calc_Calculator__classid, G_STRUCT_OFFSET (POA_calc_Calculator__epv, baza2),
(ORBitSmallSkeleton) _ORBIT_skel_small_calc_Calculator_baza2);

return _ORBIT_retval;
}
