/*
 * This file was generated by orbit-idl-2 - DO NOT EDIT!
 */

#include <string.h>
#define ORBIT2_STUBS_API
#define ORBIT_IDL_C_COMMON
#define Calculator_COMMON
#include "Calculator.h"

static const CORBA_unsigned_long ORBit_zero_int = 0;

#ifndef ORBIT_IDL_C_IMODULE_Calculator
void _ORBIT_skel_small_calc_Calculator_aduna(POA_calc_Calculator             *_o_servant, gpointer            _o_retval,gpointer           *_o_args,CORBA_Context       _o_ctx,CORBA_Environment  *_o_ev,
CORBA_long_long (*_impl_aduna)(PortableServer_Servant _servant, const CORBA_long_long a, const CORBA_long_long b, CORBA_Environment *ev)) {
*(CORBA_long_long *)_o_retval = _impl_aduna (_o_servant, *(const CORBA_long_long *)_o_args[0], *(const CORBA_long_long *)_o_args[1], _o_ev);
}
void _ORBIT_skel_small_calc_Calculator_scade(POA_calc_Calculator             *_o_servant, gpointer            _o_retval,gpointer           *_o_args,CORBA_Context       _o_ctx,CORBA_Environment  *_o_ev,
CORBA_long_long (*_impl_scade)(PortableServer_Servant _servant, const CORBA_long_long a, const CORBA_long_long b, CORBA_Environment *ev)) {
*(CORBA_long_long *)_o_retval = _impl_scade (_o_servant, *(const CORBA_long_long *)_o_args[0], *(const CORBA_long_long *)_o_args[1], _o_ev);
}
void _ORBIT_skel_small_calc_Calculator_inmulteste(POA_calc_Calculator             *_o_servant, gpointer            _o_retval,gpointer           *_o_args,CORBA_Context       _o_ctx,CORBA_Environment  *_o_ev,
CORBA_long_long (*_impl_inmulteste)(PortableServer_Servant _servant, const CORBA_long_long a, const CORBA_long_long b, CORBA_Environment *ev)) {
*(CORBA_long_long *)_o_retval = _impl_inmulteste (_o_servant, *(const CORBA_long_long *)_o_args[0], *(const CORBA_long_long *)_o_args[1], _o_ev);
}
void _ORBIT_skel_small_calc_Calculator_imparte(POA_calc_Calculator             *_o_servant, gpointer            _o_retval,gpointer           *_o_args,CORBA_Context       _o_ctx,CORBA_Environment  *_o_ev,
CORBA_long_long (*_impl_imparte)(PortableServer_Servant _servant, const CORBA_long_long a, const CORBA_long_long b, CORBA_Environment *ev)) {
*(CORBA_long_long *)_o_retval = _impl_imparte (_o_servant, *(const CORBA_long_long *)_o_args[0], *(const CORBA_long_long *)_o_args[1], _o_ev);
}
void _ORBIT_skel_small_calc_Calculator_baza2(POA_calc_Calculator             *_o_servant, gpointer            _o_retval,gpointer           *_o_args,CORBA_Context       _o_ctx,CORBA_Environment  *_o_ev,
CORBA_string (*_impl_baza2)(PortableServer_Servant _servant, const CORBA_long_long n, CORBA_Environment *ev)) {
*(CORBA_string *)_o_retval = _impl_baza2 (_o_servant, *(const CORBA_long_long *)_o_args[0], _o_ev);
}

#endif
#if ( (TC_IMPL_TC_calc_Calculator_0 == 'C') \
&& (TC_IMPL_TC_calc_Calculator_1 == 'a') \
&& (TC_IMPL_TC_calc_Calculator_2 == 'l') \
&& (TC_IMPL_TC_calc_Calculator_3 == 'c') \
&& (TC_IMPL_TC_calc_Calculator_4 == 'u') \
&& (TC_IMPL_TC_calc_Calculator_5 == 'l') \
&& (TC_IMPL_TC_calc_Calculator_6 == 'a') \
&& (TC_IMPL_TC_calc_Calculator_7 == 't') \
&& (TC_IMPL_TC_calc_Calculator_8 == 'o') \
&& (TC_IMPL_TC_calc_Calculator_9 == 'r') \
) && !defined(TC_DEF_TC_calc_Calculator)
#define TC_DEF_TC_calc_Calculator 1
#ifdef ORBIT_IDL_C_IMODULE_Calculator
static
#endif
ORBIT2_MAYBE_CONST struct CORBA_TypeCode_struct TC_calc_Calculator_struct = {
{&ORBit_TypeCode_epv, ORBIT_REFCOUNT_STATIC},
CORBA_tk_objref,
0,
0,
ORBIT_ALIGNOF_CORBA_POINTER,
0,
0
,
NULL,
CORBA_OBJECT_NIL,
(char *)"Calculator",
(char *)"IDL:calc/Calculator:1.0",
NULL,
NULL,
-1,
0,
0, 0
};
#endif

#ifndef ORBIT_IDL_C_IMODULE_Calculator
CORBA_unsigned_long calc_Calculator__classid = 0;
#endif

/* Interface type data */

static ORBit_IArg calc_Calculator_aduna__arginfo [] = {
	{ TC_CORBA_long_long,  ORBit_I_ARG_IN | ORBit_I_COMMON_FIXED_SIZE, (char *)"a" },
	{ TC_CORBA_long_long,  ORBit_I_ARG_IN | ORBit_I_COMMON_FIXED_SIZE, (char *)"b" }
};
static ORBit_IArg calc_Calculator_scade__arginfo [] = {
	{ TC_CORBA_long_long,  ORBit_I_ARG_IN | ORBit_I_COMMON_FIXED_SIZE, (char *)"a" },
	{ TC_CORBA_long_long,  ORBit_I_ARG_IN | ORBit_I_COMMON_FIXED_SIZE, (char *)"b" }
};
static ORBit_IArg calc_Calculator_inmulteste__arginfo [] = {
	{ TC_CORBA_long_long,  ORBit_I_ARG_IN | ORBit_I_COMMON_FIXED_SIZE, (char *)"a" },
	{ TC_CORBA_long_long,  ORBit_I_ARG_IN | ORBit_I_COMMON_FIXED_SIZE, (char *)"b" }
};
static ORBit_IArg calc_Calculator_imparte__arginfo [] = {
	{ TC_CORBA_long_long,  ORBit_I_ARG_IN | ORBit_I_COMMON_FIXED_SIZE, (char *)"a" },
	{ TC_CORBA_long_long,  ORBit_I_ARG_IN | ORBit_I_COMMON_FIXED_SIZE, (char *)"b" }
};
static ORBit_IArg calc_Calculator_baza2__arginfo [] = {
	{ TC_CORBA_long_long,  ORBit_I_ARG_IN | ORBit_I_COMMON_FIXED_SIZE, (char *)"n" }
};

#ifdef ORBIT_IDL_C_IMODULE_Calculator
static
#endif
ORBit_IMethod calc_Calculator__imethods [] = {
	{
		{ 2, 2, calc_Calculator_aduna__arginfo, FALSE },
		{ 0, 0, NULL, FALSE },
		{ 0, 0, NULL, FALSE },
		TC_CORBA_long_long, (char *)"aduna", 5,
		0| ORBit_I_COMMON_FIXED_SIZE
}
, 	{
		{ 2, 2, calc_Calculator_scade__arginfo, FALSE },
		{ 0, 0, NULL, FALSE },
		{ 0, 0, NULL, FALSE },
		TC_CORBA_long_long, (char *)"scade", 5,
		0| ORBit_I_COMMON_FIXED_SIZE
}
, 	{
		{ 2, 2, calc_Calculator_inmulteste__arginfo, FALSE },
		{ 0, 0, NULL, FALSE },
		{ 0, 0, NULL, FALSE },
		TC_CORBA_long_long, (char *)"inmulteste", 10,
		0| ORBit_I_COMMON_FIXED_SIZE
}
, 	{
		{ 2, 2, calc_Calculator_imparte__arginfo, FALSE },
		{ 0, 0, NULL, FALSE },
		{ 0, 0, NULL, FALSE },
		TC_CORBA_long_long, (char *)"imparte", 7,
		0| ORBit_I_COMMON_FIXED_SIZE
}
, 	{
		{ 1, 1, calc_Calculator_baza2__arginfo, FALSE },
		{ 0, 0, NULL, FALSE },
		{ 0, 0, NULL, FALSE },
		TC_CORBA_string, (char *)"baza2", 5,
		0
}
};

static CORBA_string calc_Calculator__base_itypes[] = {
(char *)"IDL:omg.org/CORBA/Object:1.0"
};
#ifdef ORBIT_IDL_C_IMODULE_Calculator
static
#endif
ORBit_IInterface calc_Calculator__iinterface = {
TC_calc_Calculator,{5, 5, calc_Calculator__imethods, FALSE},
{1, 1, calc_Calculator__base_itypes, FALSE}
};

